import random
veglist = ("Artichoke","Asparagus","Beans","peas","Broccoli","Sprouts","Cabbage","Carrots","Cauliflower","Celery","Cucumber","Eggplant","Fennel","Garlic","Lettuce","Mushroom","Okra","Onion","Pepper","Potatoes","Pumpkin","Radish","Rhubarb","Spinach","Squash","Corn","Tomato","Turnip")
veg = random.choice(veglist)
veg2 = random.choice(veglist)
veg3 = random.choice(veglist)
veg4 = random.choice(veglist)
print("Mashed",veg,"on the ceiling.")
print("Green",veg2,"on the floor.")
print("Stewed",veg3,"in the corner")
print(veg4,"upon the door.")
